; PlatformIO Project Configuration File
[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino

upload_protocol = custom
upload_command = avrdude -C $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf -p $BOARD_MCU -c xplainedmini_isp -P usb -U flash:w:$SOURCE:i

monitor_speed = 9600